name: Build and push

on:
  push:
    tags:
    - v[0-9]+.[0-9]+.[0-9]+

env:
  IMAGE_NAME: jssblck/rust-ci

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.tag.outputs.version }}

    steps:
    - name: Determine tagged version
      id: tag
      run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\/v/}

  ghcr:
    name: GHCR
    runs-on: ubuntu-latest
    needs: tag

    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: jssblck
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v2
      with:
        file: ./Dockerfile
        push: true
        tags: |
          ${{ env.IMAGE_NAME }}:${{ needs.tag.outputs.version }}
          ${{ env.IMAGE_NAME }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
